### ISSUE TITLE
Android hiscore.dat location ?

### ISSUE THREAD

**Issue by zzedmore** [libretro/FBNeo#1010]
Hi, just a quick question as I cannot find the answer anywhere i'm afraid. What is the actual location for the hiscore.dat file on Android ?

I have tried -

system/fbneo
system/fbneo/hiscores

roms directory
roms directory/fbneo

I have the Hiscore option on in the core options and run-ahead is always off.
I don't have any .hi files on my device. I have some .fs and .nv files in the saves directory.

My test rom is bombjack which is in the hiscore.dat. Any help would be appreciated.

I saw this [commit](https://github.com/libretro/FBNeo/commit/19c80dfbf6da0c69bc4a0a0996b803527c10e44e) but not sure if it applies to Android.

**Comment by barbudreadmon** [comment]
1. read https://docs.libretro.com/library/fbneo/#hiscores
2. i don't know where your `system_dir` is located so don't ask me, if you don't know either then you should be able to find that information inside your `retroarch.cfg`
3. make sure you aren't using a webpage as hiscore.dat, there is a running gag where people download the github page instead of the actual hiscore.dat file.
