### ISSUE TITLE
Keyboard key "K" doesn't work in some arcade mahjong games

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1028]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

tested commit: 11a68c64f1525a1c4c75981ba2a25394325c8eec
tested game:  mirage akiss hgkairak hotgmcki

**Comment by barbudreadmon** [comment]
Thanks for the report, fixed with https://github.com/finalburnneo/FBNeo/commit/4b8395544ab583dbc212e323b86dae50c356a424 https://github.com/finalburnneo/FBNeo/commit/4b8395544ab583dbc212e323b86dae50c356a424 and https://github.com/finalburnneo/FBNeo/commit/1ad56802a53bc11fce016960e4a41cf08905a6dd

I'll transfer all those fixes to the libretro port after checking your 3rd bug report.

**Comment by royfokk** [comment]
Since the first bug is fixed, I will close this and open new issues.
