### ISSUE TITLE
Not enough inputs for qndream.

### ISSUE THREAD

**Issue by royfokker934** [libretro/FBNeo#1059]
There is a scenario where I have to select the genre of the quiz. but how do I select the red 1,2 on the bottom right of the screen?
The only inputs are answer 1 - 4.
![Image_20231013132335](https://github.com/libretro/FBNeo/assets/26887124/621303f1-aced-43a3-9d2a-54b74d458813)
![Image_20231013132528](https://github.com/libretro/FBNeo/assets/26887124/1b4ab86a-875e-4667-8d99-365587f92a4f)

**Comment by barbudreadmon** [comment]
All buttons are mapped, maybe try P2 buttons ?

**Comment by barbudreadmon** [comment]
Did it work ?

**Comment by royfokker934** [comment]
Actually the only selectable genre is the RED options. You can choose it with button A/B. 
Button X, Y and START does not work in this screen.
I will make farther investigation.

**Comment by barbudreadmon** [comment]
I went into this game's input test : 
![qndream-231015-070356](https://github.com/libretro/FBNeo/assets/10391265/144761f1-d4fa-4d61-94c7-9cfc58369752)

All inputs on this screen are mapped and respond.
Maybe the blue choices simply mean the choices are unavailable due to some game logic ? Like a previous choice ?

Whatever the problem is here, it doesn't seem to be an emulation issue.

**Comment by royfokker934** [comment]
When I test again, the phenomenon changed again.
This time B/A/Y/X selects blue 1/2/3/4, and the red options is unselectable.
And I can't repeat what happened last time(B/A select red 1/2. not pressing B/A before time up select blue 1).
This is weired.

**Comment by barbudreadmon** [comment]
I'll close since all inputs for this game are working properly.

**Comment by royfokker934** [comment]
The red options are seleted by pressing 2P button 1/2. Thank you very much.
