### ISSUE TITLE
[Libretro] Posibility of make split (tiny) builds of FBNeo for specific drivers like MAME?

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/FBNeo#1075]
Is there any chance or posibility of making makefiles or changes for allow us to make shrunk (tiny/split) builds/cores of FBNeo, like we can do for MAME?
This is so useful for device which can't fit all FBNeo drivers on RAM memory, such low-powered PCs and even the Nintendo Wii.

Something like this that was done for MAME 2003 Plus: https://github.com/libretro/mame2003-plus-libretro/commit/a9d71ca339823520fa8ed2b0d2dfbd5462c4a0ff

**Comment by barbudreadmon** [comment]
Adding `subset=xxxxx` to the make command line will tell the build scripts to use `Makefile.xxxxx` instead of `Makefile.common` for the list of c/cpp files to use. It'll also name the core fbneo_xxxxx_libretro instead of fbneo_libretro.

There is an example for neogeo at https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/Makefile.neogeo

So [following the instructions to build this core manually](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#building-this-core-manually), you'd have to run the following afterward : 
```
make -j5 -C src/burner/libretro subset=neogeo clean
make -j5 -C src/burner/libretro subset=neogeo generate-files
make -j5 -C src/burner/libretro subset=neogeo
```

You can easily create more `Makefile.xxxxx` files to meet your needs, and if they are not too arbitrary i don't particularily mind adding them to this repo.

However, keep in mind reducing the binary size will only achieve so much, many games still require 100+ MB at runtime to be played, which is why those devices you are talking about are just a waste of time as platforms for arcade emulation. 
For the specific case of wii, using the fbalpha2012 split cores just makes far more sense, since they were heavily hacked with wii-specific code to create "virtual memory", which is something i won't add here.

**Comment by barbudreadmon** [comment]
Ok, i might have misunderstood your intention here, it seems your request might actually be to add wii builds to the libretro buildbot, so let me be clear about it : **it won't happen**.

The wii is an horrible piece of hardware heavily lacking in memory. As previously mentioned, the binary size is only the tip of the iceberg as far as memory issues are concerned, and we are not interested in implementing extremely invasive workarounds in hundreds of files in our codebase to get around this.

Beyond the memory problem, endianness and the lack of the processing power is another problem.

If anything, i have been thinking of removing the 3ds builds, where the situation is still better than wii.

If you are interested by the solution i previously proposed for your own usage, i can provide more guidelines, but this core won't become officially available on wii.

**Comment by saulfabregwiivc** [comment]
yeah but Wii is my only console here i am interested as i don't have other platforms other than Windows PC.
Also, i am aware that there won't be official FBA builds for Wii but i thought it was worth asking this for see if i could try compiling a split FBA core by myself for the Wii, for personal use.

Thanks for answering.

**Comment by saulfabregwiivc** [comment]
btw, for try by myself compiling this for Wii, i'd want to try with the driver **mystwarr** (Konami Mystical Warriors), **namcos2** (Namco System 2) and **segas32** (Sega System 32).
