### ISSUE TITLE
CHD Support for Neo-Geo CD

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#11]
With Neo-Geo CD emulation being improved in FB Alpha, integrating support for the CHD format would be the first arcade core (besides MAME) that use it. Such support could be integrated for making Killer Instinct 1 & 2 to work without extracting the files.

**Comment by ToniBC** [comment]
I'm sorry, but I do not understand how something that is relatively simple to implement is not put because it has no advantage?

According to the documentation, it supports ccd / sub / img iso (trurip), and single file MODE1 / 2352 bin / cue, that is, it supports formats like ccd / sub / img that are frankly strange and that do not bring any improvement either.

CHD the main advantage is that it is a compressed file that you can run without problems, without having to decompress, that's why it is used in MAME and other emulators. Retroarch supports this format in almost all the cores that read CD, but of course, if we want to try or use FBNeo / FBA we have to transform our isos into other formats.

They say that there is no interest in people, but there are several threads asking for support, I do not know what else they want.

**Comment by barbudreadmon** [comment]
> I'm sorry, but I do not understand how something that is relatively simple to implement is not put because it has no advantage?

Here is a commit for chd support in pcsx-rearmed : https://github.com/libretro/pcsx_rearmed/commit/ce188d4d7f3b9ad04867c49b424e8497c2ade92b , ~100000 new lines over ~330 files, you must be an awesome developper if it sounds simple to you, i'm eagerly waiting for your PR to implement it ! Thanks in advance !

**Comment by ToniBC** [comment]
I'm not a programmer, but FB uses a lot of MAME code, MAME has support for CHD, the beetle cores all read CHS (PS1, Saturn, PCE), GenesisPlus also supports CHD, the PSP (PPSSPP) supports CSO which is "similar "I do not know, it will have its complexity, but if the rest implemented it, I doubt it's something ultra complicated.

It is not the same to have an iso of 600 Mb in 2 or 3 files, with Track1, track 2, etc ... than a single file of 300/400 Mb.

Obviously reading the direct files is easier, but do not say that it does not offer advantages when others included it, because it offers a great advantage and more when we talk about devices like Raspberry and the like.

You can look to see who integrated the CHD support in the other projects and ask for help, that's what the open source projects are for.

**Comment by barbudreadmon** [comment]
> I do not know

Exactly, so don't act as if you know.

> do not say that it does not offer advantages when others included it

Are you another member of the CHD fanboys paranoid club ? Between the libretro forums and github, i'm **really** getting sick of the lies you guys keep repeating because you feel frustrated : **i never said there is no advantages**.

> You can look to see who integrated the CHD support in the other projects and ask for help

What i see is implementations backed by bounties of several hundred dollars, i've some doubts they would help for free.

Again, yeah it's certainly better, but i'm not interested, and upstream is not interested either. And in my case, having CHD fanboys trolling or insisting every single month of the year is a complete turn off.
So if you want it, you'll have to either implement it yourself, or find someone that will implement it **for free**. Good luck or move on !

**Comment by klepp0906** [comment]
so after a brief read through - am i correct in assuming chd support cant be added unless it is done for free as FBN + bounties = no bueno?  Or was this something pre-split/old github that can now have a bounty re-made/opened?

**Comment by barbudreadmon** [comment]
No bounty, that's against FBNeo's license

**Comment by klepp0906** [comment]
yikes, so we need to find someone nice enough to do it for free.  Sounds substantially more tricky.   Thank you for the info though.  Saves me from starting a bounty and having it purged :P

**Comment by tmaul** [comment]
This branch was a proof of concept but I couldn't get it working correctly and I have no interest in looking again. Also my latest merge with master has screwed up the project files on that branch so it's not even building. 

https://github.com/tmaul/FBNeo/commits/chdsupport

**Comment by barbudreadmon** [comment]
Thanks @tmaul, i'm also adding this commit from another project as reference for anyone wanting to deal with this task : https://github.com/libretro/neocd_libretro/commit/e4b6e99d3452ee9d0006cafd63e1dd66e57a3824

**Comment by klepp0906** [comment]
> This branch was a proof of concept but I couldn't get it working correctly and I have no interest in looking again. Also my latest merge with master has screwed up the project files on that branch so it's not even building.
> 
> https://github.com/tmaul/FBNeo/commits/chdsupport

ah, so at least that gets someone part of the way there i imagine.  Thanks for taking a shot at it <3

**Comment by tmaul** [comment]
If anyone was going to take a look, this commit was the one that was building (in visual studio) and attempting to run the chds.

https://github.com/tmaul/FBNeo/tree/c0d164746d68169384324a1a201065fea57d6ae6
