### ISSUE TITLE
80's cocktail cabinets  - "unflip" and fix broken graphics

### ISSUE THREAD

**Issue by furiadeoso** [libretro/FBNeo#116]
Hi!,

Black Tiger,  two players (turn based) . When  player 2 are playing the screen rotates.
Watch the video: https://youtu.be/USyl8YGCkNw?t=40

**Comment by dinkc64** [comment]
It's fixed, and will be in soon :)  A lot of old games are like this, because 2-joy games meant that the cabinet was Coctail-style.

**Comment by furiadeoso** [comment]
Thanks @dinkc64 !

**Comment by dinkc64** [comment]
ok, now fixes are in for:
centipede/millipede, speed rumbler, blk tiger, gunsmoke.

Now, for some bad news: almost all 80s games works like this - 2 settings in dips:
upright cabinet setting: 1 joystick shared for 2 players
cocktail cabinet setting: 2 joysticks for 2 players, but 2nd player screen is flipped or "broken / bad graphics".  a lot of cocktail dip-setting was removed (by us) because of bad graphics :(

I would like to slowly fix them all for cocktail setting ("unflip" and fix broken graphics).  I think this will be useful for netgames.

For now, I like to focus on fixing just "favorites" games,  If you have some that needs 2p cocktail fixed for netgaming (or anyting), reply here :)

best regards,
- dink

**Comment by furiadeoso** [comment]
Thanks very much, @dinkc64 . We will make in my community a "favourite" games list to fix and paste here.

**Comment by dinkc64** [comment]
sounds good :)

**Comment by fastpop72** [comment]
Crazy Climber (cclimber) suffer this issue...

**Comment by barbudreadmon** [comment]
Closing this issue, if there are any other issue like this it might be better to open them upstream, since i don't think that kind of issue could only affect the libretro port.
