### ISSUE TITLE
decocass broken

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#123]
launching any game utilizing decocass somehow threw a 'CASSETTE 01 ERROR!' on start-up.

**Comment by barbudreadmon** [comment]
Tried all non-clones from this driver, i'm not getting this error, however i've buggy end of bios screen for the following games :
- cflyball
- coozumou
- cfghtice
- czeroize
- cpsoccer

Something like this : 
![cflyball-190803-080820](https://user-images.githubusercontent.com/10391265/62408381-9e928580-b5c8-11e9-8d4d-bda82b7cf22d.png)

@arnoldsecret Your platform is windows, right ? Can you test on standalone ? Also, are you using any specific RA feature or core option ?

**Comment by arnoldsecret** [comment]
standalone works, once again, I never touched on any RA feature.

**Comment by dinkc64** [comment]
barbudreadmon, The weird screen changes are due to the game changing the graphics and characterset to new characters while the game is loading.  Those specific games utilize every last byte of the decocass system and don't have memory left over to do it "behind the scenes" like the others - also it happens on real HW too.

I'm afraid I've never seen the cassette 01 error...

best regards,
- dink

**Comment by barbudreadmon** [comment]
Maybe make sure your `decocass.zip` isn't corrupted by unzipping it ? I think you had a similar issue some months ago.

PS : the glitch is not a glitch actually, it's documented in the driver

**Comment by arnoldsecret** [comment]
closed, updates fixed it

**Comment by barbudreadmon** [comment]
Always make sure you are running the latest version when reporting an issue.
