### ISSUE TITLE
"Mouse (Ball only)" symlinked to Left Analog control only.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#127]
In games like "Blades of Steel" that uses Right Analog (Trackball) to control, the "Mouse (Ball only)" does not work.

**Comment by barbudreadmon** [comment]
Thanks for the report, i noticed a few things which seems wrong with this driver and how i handle controls for it (i thought it was using some kind of dual stick control scheme but it doesn't seem to be the case)

So : 
- bladestl is a joystick only game, the cabinet had no support for trackball
- its clones bladestll and bladestle had trackball support on the cabinet, however i suspect it's not implemented in the FBNeo driver, which makes those clones unplayable for me because joystick doesn't seem to work either (need confirmation from upstream about this)

I understand the confusion, the 3 romsets share the same InputList which contains both analog and digital inputs. For now i only fixed the names upstream to match with MAME (https://github.com/finalburnneo/FBNeo/commit/3c86e416f84a8762b1d3ee7eca81b31ca848a2c8), let's wait for @dinkc64's answer.

**Comment by barbudreadmon** [comment]
@dinkc64 Thanks !

@fastpop72 Fixed

Closing

**Comment by dinkc64** [comment]
:)
