### ISSUE TITLE
Can't load optional bios files

### ISSUE THREAD

**Issue by Traace** [libretro/FBNeo#130]
Hi, I've noticed that when I load FBNeo core and its proper infofile (git-version) in current retroarch stable it shows all optional bios files as "missing" without listing the proper md5 string.

This is very confusing because my system folder contains all these optional bios files.

I'm searching for hours now, really trying to find a solution for this issue.
I already moved the folder to another location and changed the path in retroarch's config. However it didn't change anything.

I'am using Linux, the folder permissions are correct. My Filesystem is case sensitive, the bios .zip files are all lower case.

Other cores load its optional bios files just fine.

Isn't this core ready yet? Or did I miss something?

**Comment by bparker06** [comment]
If you look inside the actual info file, the issue seems clear:

```
firmware0_desc = "neogeo.zip (Neo Geo BIOS)"
firmware0_path = "fbneo/neogeo.zip"
```

It's looking in an `fbneo` folder for files when it's not actually displaying that fact in the description... so you're probably putting them directly in the system folder which is wrong. The info file should be modified to include the extra folder in the descriptions.

**Comment by Traace** [comment]
OH! damn. Many thanks for the hint, they are all present now 👍  (had a pretty long yesterday). We can close this already.

I also tried to run retroarch verbose but cores don't output error strings in console if they can't find the files, they remain silent. While retroarch is awesome already, this is something we can improve.
