### ISSUE TITLE
Cyclone doesn't work with neogeo MVS/UniBios (but does with AES)

### ISSUE THREAD

**Issue by neogeo-user** [libretro/FBNeo#144]
Hi,

I'm running FBNeo on a Raspberry Pi Zero, version build `13ee6ae` (from RetroPie binary).

Running any number of neogeo games (I've tried kof98, kof2002, samsh5sp, samsho2), if I've got cyclone set in libretro's options menu, the game will simply show a black screen (not even the bios screen) if the bios is set to MVS or UniBios. There is nothing odd in the runcommand.log log (even with verbose logging), and it doesn't crash. It does work fine if the bios is set to AES though (it starts working straight away, no need to restart).

If cyclone is unset, MVS and UniBios work fine (after restarting of course). I've got a verified correct romset, including neogeo.zip, according to the datfile installed alongsisde FBNeo.

I've also tried this on a Raspberry Pi 2 (also from binary) and the same happens.

Would love to be able to run these titles with cyclone on for performance. Thanks for all the hard work.

**Comment by barbudreadmon** [comment]
I spent last few hours trying to debug this, i've no clue what's going on, it seems this issue has always been there, it doesn't seem to affect every mvs neogeo game though (i tried nam1975 & kof94, they worked). Honestly i'm thinking of tagging this as `wontfix`, in the first place the core option is pretty clear about its usage : 
https://github.com/libretro/FBNeo/blob/3e7e59dacf026de4020b5a77c964c33da19a547b/src/burner/libretro/retro_common.cpp#L205-L206

Maybe @dinkc64 would have some clues about this ? Otherwise i don't think i can solve it.
One thing that might be worth mentioning : the "green artifact screen" when using MVS is appearing twice before the screen goes black (with musashi it's appearing once then it goes to bios screen), and unibios is only showing a red screen.

**Comment by neogeo-user** [comment]
Thanks for looking into it @barbudreadmon.

Having had a quick look, the only thing I can contribute to help is that maybe changing the `bprintf` calls in [`src/cpu/c68000_intf.cpp`](src/cpu/c68000_intf.cpp) (and uncommenting some of the commented ones) so that they log might help, since there seems to be a lot of them already.

**Comment by barbudreadmon** [comment]
I already looked into the printfs, as far as emulation goes, cyclone is up and running without complaining about anything.

**Comment by dinkc64** [comment]
It sounds to me that cyclone has some emulation issues :(

**Comment by barbudreadmon** [comment]
Yeah, in the first place, there are some warnings about unemulated instructions in the cyclone source code
