### ISSUE TITLE
[3DS] Error loading roms larger than 25 MB (NeoGeo)

### ISSUE THREAD

**Issue by ToniBC** [libretro/FBNeo#188]
It is a curious mistake that I try to explain because it has a partial solution and is very strange.

When we try to load NeoGeo roms into a 3DS or N3DS of more than 25 MB, Retroarch gives a bad error, this happens with FBNeo and with FBA 2012 normal or NeoGeo version.

Now, everything seemed to indicate that it was a limitation of memory-related 3DS, but it seems not.

For example:

We have the rom "mslug4.zip" of 60 MB, if we load this rom with FBA 2012 or FBNeo, crash.

But if we create a dummy file with the same name and extension 7z, that is to say “mslug4.7z” and put it in the same directory of the original rom. If we load the rom dummy with FBA 2012, the game magically loads without problems and works with all roms of more than 25 MB.

The problem is that FBA 2012 is very old and its emulation has more errors than FBNeo, it would be nice to solve this error and use FBNeo.

PD: If you load the dummy file with FBNeo it gives the same error as always, it only works with FBA 2012.

Thank you.

**Comment by barbudreadmon** [comment]
There are hacks by @wiimpathy in fbalpha2012 for memory-limited environment, those hacks look terrible, i don't want them in fbneo.

**Comment by Wiimpathy** [comment]
Are you talking about this : https://github.com/libretro/fbalpha2012_neogeo/commit/526c6c052c6998801fdad365ad1c49897769ead3

I know it's very far from perfect but what's so terrible? It's only for the Wii and the code is not invasive.
It's not easy either due to the non-contigous memory(no mmap) unlike other low-specs platforms. And there's even less RAM than 3DS(about 75MB)!
The low level part is great and not from me : https://raw.githubusercontent.com/libretro/fbalpha2012_neogeo/master/src/burner/libretro/wii_vm.c

Maybe, it's not intended but your answer is quite arrogant and bit offensive.
Anyway, any help and suggestions are welcome!

**Comment by ToniBC** [comment]
I understand that it may not be a very nice solution, but if with a "trick" or fix the games are loaded, ram limitation is not, the 3DS has 128 Mb and the N3DS has 256 Mb.

I think the game loading system would have to be checked a bit, if a normal NDS can load NeoGeo games, you are too.

The problem with FB2012 is that it has more emulation errors, but it manages to load the games.

I do not know, I think it is something to consider in the port of this emulator for the New 3DS for example, if with the 3DS you can not, the New if that could in theory.

**Comment by barbudreadmon** [comment]
@Wiimpathy i was talking about the commits to make the fbalpha2012 cores work on wii in general (i think there are more than 1 commit), i looked at them a few months ago, they seemed totally invasive to me. Sorry if i was offensive, that's just my point of view as the guy who'll have to deal with the maintainance of this core.

> The problem with FB2012 is that it has more emulation errors, but it manages to load the games.

That's the other reason i'm not interested in this, neogeo emulation changed a lot between 2012 and now, it seems fbneo is currently the most faithful neogeo emulator available (better than mame), the requirements are a lot higher (probably twice the cpu charge). Afaik, the wiiu can't even handle full speed sega system16 emulation with fbneo, i have serious doubts 3ds/n3ds/wii would do any better with a system that is more demanding like the neogeo.

**Comment by Wiimpathy** [comment]
@barbudreadmon Ok, I get it. It's not related to the VM code and the fbalpha2012_neogeo
 core.
That's when I've added wii lightgun support in fbalpha2012. Since there were no lightgun at all in this core, I've taken the latest libretro fba's code and removed neogeo thinking it was ok because there's already a fba2012 dedicated core for that.
I knew it wasn't the best idea but no infinite time to implement lightgun in retroarch, check in 5 cores if it's working etc.

**Comment by ToniBC** [comment]
@barbudreadmon I did not mean to continue developing FBA2012, I was referring to whether you could find a solution in the loading of large roms in FBNeo, because the rest of the games that load work perfect in FBNeo in 3DS, and the only problem is that crash with roms of more than 25 Mb, and if the older emulator like FB2012 can load them with some trick, implement something similar in FBNeo so that it can load them.

I don't know, using a cache for those big games, that I saw something similar for the Wii, or some other stuff, while they load, the operation of the Neo-Geo in FBNeo is correct.

**Comment by barbudreadmon** [comment]
feel free to send a PR, if it's not too invasive i'll accept it

**Comment by ToniBC** [comment]
Sorry, I think I put wrong who would say the message, I mess a little with github, sorry if I put it wrong.

Thank you for the effort and if at any time you get any progress on this, many people are waiting for you. In the GBATemp forums, in the Retroarch thread they are testing with hope in each version if NeoGeo manages to load, but there are many cores and many things to improve, I just wanted to comment so that the error is recorded.

Thank you anyway.
