### ISSUE TITLE
Regression with ironclad

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#213]
In the latest build, both `ironclad` and `ironclado` refuse to get past the boot sequence, ending up in a black screen.

**Comment by barbudreadmon** [comment]
This game works only with specific bioses, set "Neo-Geo mode" to dipswitch and it'll work (except if your `neogeo.zip` romset is incomplete).

However, there might be a regression with the "Neo-Geo mode", a few years back i think the setting was ignored for that kind of games. 

Well, i have been saying this for years but this time i might really consider removing this core option if i don't figure out where this regression is coming from, the proper way to set bioses in fbneo has always been to use dipswitches, "Neo-Geo mode" is just a hacky shortcut, furthermore there is a lot of confusion because of this core option.

**Comment by barbudreadmon** [comment]
Fixed, the issue appeared when i updated the core options system 6 months ago for compatibility with newer retroarch (i had a feeling there would be regression at that time, because fbneo's core option system is so complex). Now it'll properly prevent the user to set a bad bios.

Thanks for the report !
