### ISSUE TITLE
game "fantasy" samples issues

### ISSUE THREAD

**Issue by leov30** [libretro/FBNeo#298]
A game called "fantasy" dosen't exist therefore rom-managers will never show fantasy.zip samples as missing.
<game name="fantasyg" cloneof="fantasyu" romof="fantasyu" sampleof="fantasy">

the parent game aslo asks for samples of "fantasy"

<game name="fantasyu" sampleof="fantasy">

**Comment by barbudreadmon** [comment]
It's extremely misleading but yeah, it works that way, from what i'm seeing about this romset in MAME history, there was a `fantasy` romset with a `fantasy` sample, the romset was later renamed to `fantasyg` and became a clone of `fantasyu`, while the sample stayed with the original name.

Tbh, i think it would have made sense if MAME renamed `fantasyu` to `fantasy`, or renamed the sample to `fantasyu`, but they didn't and they might have their reasons, so we won't change this either because we try to keep the compatibility high between MAME & FBNeo romsets.

Is there an actual issue with playing those samples ? If not i'll close.

**Comment by barbudreadmon** [comment]
Actually, let's tag @osso13 about this, he did the [change](https://github.com/mamedev/mame/commit/54b805b89d3d016f0ea994e0b72a194edfc76898#diff-4eabe02731d4257c84e61655a152e98b) so he might be able to give a full explanation.

**Comment by Osso13** [comment]
Hi,
samples work fine (at least in MAME) and I've kept them as fantasy because they aren't unique to fantasyg or fantasyu. If and when a World version of Fantasy will be dumped the romset will be named fantasy.

**Comment by leov30** [comment]
Testing the data file in romcener i found that romcenter creates "fantasy (romcenter)" sample
without needing the game "fantasy" in the data.
so  it seems that theres no issues regarding the game "fantasy" not exising in the dat.

**Comment by barbudreadmon** [comment]
> when a World version of Fantasy will be dumped the romset will be named fantasy

@Osso13 so that's the reason, thanks for explaining :)
