### ISSUE TITLE
Filename-based subsystem selection non-functional

### ISSUE THREAD

**Issue by Sanaki** [libretro/FBNeo#347]
Supposedly you should be able to launch "bonk3.7z" from the tg16 set via subsystem > tg16 > pick game (works fine, though not viable for my purposes), launching tg16/bonk3.7z (that one works fine), or launching "bonk3_tg" with no extension. The last one isn't functional, nor does it work as "bonk3_tg16" or with extension present. I did notice that subsystem names seem to have changed to match the directory names at some point. Is this just a discarded feature that needs to be scrubbed from the readme?

Source: https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/README.md#emulating-consoles

To be clear: I have no interest in using this naming scheme, since it isn't how my rom manager names the games anyway. I like the subdirectory names, they work fine. We're sorting out how to handle FBNeo subsystems over at RetroAchievements though, and knowing if this feature is merely bugged and will be functional later is important.

**Comment by Sanaki** [comment]
This is why I shouldn't troubleshoot while waking up. Prefix, not suffix, and it does work via "tg_bonk3".

**Comment by barbudreadmon** [comment]
> launching "bonk3_tg" with no extension. The last one isn't functional, nor does it work as "bonk3_tg16"

What should be functional is `tg_bonk3`, however it seems the "subsystem identified from parent folders" partially broke it (it won't work if the romset is inside a tg16 folder, whether you disabled the core option or not). I'll try to fix that

**Comment by Sanaki** [comment]
It launches just fine as tg16/bonk3.7z from within retroarch, just not from CLI.

**Comment by barbudreadmon** [comment]
yes, the "subsystem identified from parent folders" works a bit too well, to the point it's always enabled, and because of that, the core is internally trying to load `tg_tg_bonk3` instead of `tg_bonk3`...

**Comment by barbudreadmon** [comment]
Long story short and to make things clearer for the lambda user : for FBNeo the internal name of those drivers is that prefixed name (i.e `tg_bonk3`), and the folder & subsystem methods are just means to transform a filename (i.e `bonk3.7z`) into what we need (i.e `tg_bonk3`)

So i further investigated the issue and i've to say it's impossible to disable the "Load Subsystem from Parent Folder" with current RetroArch api limitations : it's a regression. Some explanation : sometime last year, when core options v2 were introduced, the number of core options you declare in a core became strict, meaning if you declare 5 core options you can't declare 6 core options later, for those reasons, because the number of core options in FBNeo is dynamic per game, **the core options have to be generated after figuring out the driver (aka game) we are running**, however for this "Load Subsystem from Parent Folder" to be togglable, **i would need to check core options variables (hence having generated them) before computing the string for the driver**.

**Comment by Sanaki** [comment]
You may want to look at how cores like Snes9x handle the "Show Advanced Audio/Video Settings", where toggling that option and cycling the quick menu will add (or remove) a number of options in that menu. That seems to go against what you're saying.

**Comment by barbudreadmon** [comment]
> That seems to go against what you're saying.

Nope, in that core all the core options already exist, it's just their visibility which is toggled. In FBNeo  that's not something we can do since we have no means to know all core options before knowing the game we'll run.

**Comment by Sanaki** [comment]
Ah, I see. Well, there goes that idea.

**Comment by barbudreadmon** [comment]
So i removed the core option since it can't work and reworked the code to prevent `tg_tg_bonk3` from happening. It's more like a workaround but that'll have to do.
