### ISSUE TITLE
Cpu downclock/overclock not working on doubledragon

### ISSUE THREAD

**Issue by QcSamuel** [libretro/FBNeo#351]
so double dragon is known for it's constant slowdown but the overclock option doesn't remove them or improve the framerate
same with the downclock on 25% the game speed is still the same with clock 100%
tested rom
ddragon.zip
ddragonb.zip
retroarch 1.8.8 apple ios
fbneo 0.2.97.44 153de63cb

**Comment by barbudreadmon** [comment]
While downclock/overclock isn't implemented for all games, ddragon seems to have that implementation, any thoughts @dinkc64 ?

**Comment by dinkc64** [comment]
I added debug code to the driver and the game is running double the cycles for 200%, but for a lot of games (and especially consoles like the sms.. and this game), you can throw all the cpu cycles you want at it, and it's still going to run at the same speed because it's synchronized to the frame/frame irq's (vblank etc).  If you want to experiment further and try to find more info on how/why it works like this, be my guest :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
That's fine by me, i'll tag this as wontfix then

**Comment by QcSamuel** [comment]
> I added debug code to the driver and the game is running double the cycles for 200%, but for a lot of games (and especially consoles like the sms.. and this game), you can throw all the cpu cycles you want at it, and it's still going to run at the same speed because it's synchronized to the frame/frame irq's (vblank etc). If you want to experiment further and try to find more info on how/why it works like this, be my guest :)
> 
> best regards,
> 
> * dink

hey so the mame core as now the cpu overclock feature and with this the slowdown is gone but not with the fbneo oc

**Comment by barbudreadmon** [comment]
I figured out the problem, the ddragon overclocking situation should be better now
