### ISSUE TITLE
Hustle (Gremlin, 1977, Blockade hardware) doesn't spawn point targets

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#416]
**Summary:**
In game, targets are supposed to spawn with point values. These targets do not appear.

**FinalBurn Neo Version Tested**
Built from source using RetroPie 3ee3337. Also tested be6bf3d on Windows 10  x64 with the same result.

**Current Behavior**
Game doesn't wait for coins to be entered before displaying Start screen. When you start the game, point targets never spawn. The player simply moves around the arena until the time runs out.

**Expected Behavior**
(Reference MAME 0.222 for correct behavior)
Game waits for coins to be inserted before displaying Start screen. In-game, targets with point values spawn. The player collects them to earn points.

Looks like a major rewrite of the blockade driver (which this is based on) was released in MAME 0.184.

**Comment by barbudreadmon** [comment]
It seems there is an issue with the "Free Game" dipswitch, a temporary fix is to set it to anything but 11000. It needs more investigation for a proper fix (the dips doesn't even show on standalone so there is clearly something wrong with it).

Btw, since you have access to the game on latest mame, could you check 2 things : 
- the "Free Game" dipswitch exists on mame ?
- setting it to 11000 is causing the same issue ?

**Comment by adelpha** [comment]
The "Free Game" dipswitch does exist in MAME.
The game works fine at all settings of "Free Game", including 11000.

**Comment by barbudreadmon** [comment]
fixed with https://github.com/finalburnneo/FBNeo/commit/3e835bf24c6959d9b4e0fd080c3f5d95bafa3b0f
