### ISSUE TITLE
dmnfrnt crashes retroarch

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#58]
Seems the PGM driver's still problematic on the libretro front, verbose stops at saving core options.

Windows 8.1 x64

**Comment by barbudreadmon** [comment]
That's weird, the game didn't have issues last time i checked it (right after https://github.com/libretro/FBNeo/commit/c5c1e67f272edf587ecca02eb989b4d8bf0ebbb9), and i don't think there was a commit affecting it since then. I'll check when i'm back home, in the meantime maybe make sure you don't have a corrupted eeprom for it ?

**Comment by arnoldsecret** [comment]
both dmnfrnt and pgm matched what's inside the dats.

**Comment by barbudreadmon** [comment]
i'm talking about the eeprom, not rom. eeproms are what are saved on your disk when you start a game, basically they are game settings.

**Comment by arnoldsecret** [comment]
well I don't see dmnfrnt's eeprom generated on the fbneo folder in system, when I tried kov it did generate the eeprom.

**Comment by barbudreadmon** [comment]
It's running perfectly fine here : 
- could you confirm you are using the latest version of FBNeo ?
- what's your platform ?
- please provide logs

**Comment by arnoldsecret** [comment]
Latest commit, using standard windows RA, can't generate log file, seems like it threw a -help everytime I try to log it.

**Comment by barbudreadmon** [comment]
Helping will be impossible if i can't reproduce your issue and you can't provide me logs (or crash information if there is a crash), maybe try with a fresh install of RA + FBNeo ? At this point i don't think that's a core issue.

**Comment by arnoldsecret** [comment]
I tried testing on a fresh RA + FBN install, still crashing.

[Here's the log.](https://github.com/libretro/FBNeo/files/3280304/retroarch-log.txt)

**Comment by barbudreadmon** [comment]
I'm not sure it's 100% fresh though : 
> [INFO] Environ SYSTEM_DIRECTORY: "C:\games\SimplePC\RetroArch\system".
[libretro INFO] Setting system dir to C:\games\SimplePC\RetroArch\system

On a sidenote, i would recommend not storing bioses at the root of system_dir : 
>[libretro INFO] [FBNEO] Using ROM with good CRC and name pgm_t01s.rom from archive C:\games\SimplePC\RetroArch\system\pgm
[libretro INFO] [FBNEO] Using ROM with good CRC and name pgm_m01s.rom from archive C:\games\SimplePC\RetroArch\system\pgm
[libretro INFO] [FBNEO] Using ROM with good CRC and name pgm_p01s.u20 from archive C:\games\SimplePC\RetroArch\system\pgm
[libretro INFO] [FBNEO] Using ROM with good CRC and name pgm_p02s.u20 from archive C:\games\SimplePC\RetroArch\system\pgm
[libretro INFO] [FBNEO] Using ROM with good CRC and name ddp3_bios.u37 from archive C:\games\SimplePC\RetroArch\system\pgm
[libretro INFO] [FBNEO] Using ROM with good CRC and name bios.u42 from archive C:\games\SimplePC\RetroArch\system\pgm

The reason is that MAME uses a different content for some bios, and that's the case for `pgm.zip` (fbneo has a few additional files in it), that's why the root of system_dir is only used as a last resort fallback with this core (it's checking for bios/parent in this order : rom_dir > system_dir/fbneo > system_dir)

I don't think your issue is related to any of the above though. I've no idea what's your issue here, maybe i could if you can provide information about the crash ?

**Comment by arnoldsecret** [comment]
it only says 'retroarch.exe has stopped working', no clarification on why it crashed.

**Comment by barbudreadmon** [comment]
Corrupted zips happened to me a few times too, what's surprising here is that the core somehow managed to read them for file list and crcs.

**Comment by dinkc64** [comment]
I wonder if RA is testing the crc of the data after it loads in the file, to make sure it matches up?

**Comment by barbudreadmon** [comment]
The libretro port search by crc, then fallback to name when it can't find the crc.
