### ISSUE TITLE
3dsx no longer runs on (New) 3DS: "An exception occurred"

### ISSUE THREAD

**Issue by vaguerant** [libretro/FBNeo#697]
![2021_03_30 10_10 PM Office Lens](https://user-images.githubusercontent.com/5259025/112987996-0c80bd00-91af-11eb-910f-c23c830cec99.jpg)

Attempting to launch the 3dsx FBNeo core from 1.9.1 stable results in the above error screen. I have not tested the installed CIA equivalent.

Using nightlies from the libretro buildbot (and Archive.org), the closest I was able to refine this issue down to was:

* 2020-11-18: **working**
* 2021-03-17: **broken**

Unfortunately, the buildbot has no older than 2021-03-17 and Archive.org has no newer than 2020-11-18, leaving a four month gap during which the issue appeared.

It's worth noting that the New 3DS is one of the more memory-constrained platforms RetroArch runs on, so it seems possible that there's no code change responsible, but just that newer FBNeo builds are hitting the ceiling of available memory on N3DS.

**EDIT:** I will take another shot at removing some drivers tomorrow to see if I can get it running; today the closest I was successful with was rolling back and building an older version.

* 2021-01-20 (50b525ff8): **working**
* 2021-03-17: **broken**

**EDIT2:** After successfully stripping out enough drivers to bring the binary size down below known working versions like 50b525f, the core still crashes just the same. I now suspect memory constraints might be a red herring and there actually *is* a code change responsible, so I've gone back to building stock revisions.

* 2021-01-20 (50b525ff8): **working**
* 2021-01-21 (df99a7b): **working**
* 2021-01-22 (550f725): **broken**
* 2021-01-27 (2d20cb2): **broken**
* 2021-01-29 (2a5e010): **broken**
* 2021-02-07 (3a4458c): **broken**
* 2021-02-19 (9538dca): **broken**

**EDIT3:** OK, the commit where FBNeo stopped working on 3DS is 550f725.

Here's the comparison from the last working version to the first non-working version: df99a7b...550f725. If nothing in that pull from upstream broke anything, then it can really only be a memory issue.

**Comment by Midnoclose** [comment]
Why was this closed? I've been getting this problem on latest commit. SF2 works, but pacman and galaga do not.
![crash image](https://user-images.githubusercontent.com/24860483/148179873-58ecaa7c-9597-4c82-9651-d1876d5454c0.png)

**Comment by barbudreadmon** [comment]
>Why was this closed?

Those issues are about a 3ds lack of memory, there is nothing we can beyond removing support for games, which is what i did last year for 3ds buils, and it somehow managed to get it small enough to run on n3ds. What's your 3ds model ? If it's one of the older 128MB models there is nothing i can do, if it's a n3ds model maybe i can try removing even more games from the 3ds build.

**Comment by Midnoclose** [comment]
It's the 256MB n3ds.

**Comment by barbudreadmon** [comment]
Please provide logs before i start removing even more games from the 3ds builds.

**Comment by barbudreadmon** [comment]
The more i think about it, the more i think this is a RetroArch issue related to rotation. Please try something for me : set `Settings > Core > Allow Rotation` to `Off` and see if those 2 rotated games (galaga & pacman) are still crashing afterward.

**Comment by barbudreadmon** [comment]
@vaguerant investigated, it turns out this issue happens when loading games consecutively without rebooting, meaning it's most likely a memory leak issue. I don't think it's coming from the core because i checked for memory leaks several times already over the years, most likely it's coming from RetroArch (which is not my business tbh), but i'll do another thorough check of my code soon anyway.

**Comment by barbudreadmon** [comment]
I confirm my previous statement : there is no memory leak in this core, this is most likely a RetroArch issue.

**Comment by Midnoclose** [comment]
I think this is a retroarch issue as well because I tried mame2003-plus and the exact same crash happened. Funnily enough, on mame2003-plus pacman runs fine but sf2 crashes.

**Comment by barbudreadmon** [comment]
>I think this is a retroarch issue as well

As i've been saying, this is first and foremost an issue about 3ds not having nearly enough memory to run a project like FBNeo. This project should probably be removed altogether from 3ds buildbot since it's not gonna improve with our daily additions.

You are supposed to be able to run pacman/galaga with FBNeo as long as it's the first thing you do after booting your 3ds, maybe the same is true for sf2 and mame2003+.

Also, yesterday, i removed some more "demanding" games from 3ds builds, not sure it's gonna help a lot but maybe give it a try. Otherwise, the fba2012 cores are far smaller and undoubtly better fits for such an ultra low-end device.
