### ISSUE TITLE
Better handling of inputs

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/FBNeo#71]
3 objectives : 
- have dynamic list of device type by system/game
- split hybrid inputs to different devices (i.e. device 1 is gamepad, device 2 is keyboard, ...) so that we can benefit from remapper (remapper is dependent on device type)
- handle mahjong games in the process (mahjong keys on a keyboard device, so we can remap them)

I'll start working on this whenever i can, also tagging @fr500 in case he has other suggestions.

**Comment by fastpop72** [comment]
It possible to add the ability to map two commands to the same button?

It would be useful to map on games like assault or vindictr because they use two sticks to move the left and right girdle, so with a single Joy-Up press i can go forward and so on....

I know mame use a separate menu to map the game-specific buttons and you can assign more buttons to the same command.

About the better handling of inputs i think it would be great to have a 'controls' menu where the specific game commands like P1-Up, P1-Down, P1-Button1, P1-Fire, P1-Jump, P1-Accelerate, P1-Gear, P1-FireUp, etc.. are on the left side of the menu and on the right you can assign the corresponding joypad button (or more than 1 button that it would be great).

**Comment by barbudreadmon** [comment]
> It possible to add the ability to map two commands to the same button?

That's fontend stuff so it's unrelated to this repo & issue. What you want is macro support in RA (RetroArch).

> About the better handling of inputs i think it would be great to have a 'controls' menu where the specific game commands like P1-Up, P1-Down, P1-Button1, P1-Fire, P1-Jump, P1-Accelerate, P1-Gear, P1-FireUp, etc..

That's fontend stuff so it's unrelated to this repo & issue. Iirc it's how it worked in the past so i doubt the RA maintainers will revert it, they most likely had reasons to change, and honestly i prefer the current way to remap.

**Comment by barbudreadmon** [comment]
i believe situation is now ok with https://github.com/libretro/FBNeo/commit/a1bb91c8b2f020b65b1b611d260cee4f282a8f8d , can you give it a try ?
