### ISSUE TITLE
RetroAchievements support

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/FBNeo#735]
@meleu @leiradel after someone mentioned it didn't work at https://www.reddit.com/r/RetroArch/comments/mx9uwm/genesis_mortal_kombat_1_six_button_mode/gvqm9ud/?context=3, i tried to add support for cheevos in md/sms/gg/ngp/nes/fds drivers, i'd like to know if it's ok now ?

**Comment by meleu** [comment]
Wow! I didn't know FBNeo was expanding its emulation scope.

Let's also ping @jamiras, @sanaki and @televandalist and see if they can test it.

**Comment by televandalist** [comment]
> Wow! I didn't know FBNeo was expanding its emulation scope.
> 
> Let's also ping @Jamiras, @Sanaki and @televandalist and see if they can test it.

We actually have quite a few FB Neo versions of PC Engine games linked. Also a few SG-1000 and MSX games. We gotta use your tool to link them, though. :)

**Comment by barbudreadmon** [comment]
> Wow! I didn't know FBNeo was expanding its emulation scope.

Actually, some of those home consoles have been there for a very long time already :)

**Comment by Sanaki** [comment]
Well this is unexpected. Didn't think it'd be something even reasonable to request, much less in the "hey, I saw this and thought I'd fix it" category. It'll take a bit to test, but this is definitely exciting.

**Comment by Sanaki** [comment]
Found a bit of time to test. All games listed in this comment are left linked to their respective RetroAchievements entries for the time being, though the cheat search in RetroArch should be sufficient to verify most of this.

NES:
* SRAM is unmapped ($6000-7FFF)
* Exposure seems a bit dodgy in general. `Spacegulls` for instance always seems to show nothing but zeroes for the memory. `Final Fantasy III` shows the same in RALibretro (may be a RALibretro bug, not sure), but shows some actual memory exposure and movement in RetroArch. This may be a timing issue, or may be related to mapper in some fashion (4 for FF3, 2 for Spacegulls). I didn't test further at this time.

FDS:
* Memory in RetroArch is static, and thus unusable. Tested `Smash Ping Pong`. FDS has no mappers or other notable variability in memory needs, so I didn't see the need to test further.

SMS:
* Looks good, tested `Asterix v0` and `Wonder Boy in Monster Land (EU/US)`. Not sure what games for SMS have battery saves, so that should still be tested.

GG:
* Looks good, tested `Tails no Skypatrol`. Similar to SMS, not sure which games have battery saves, if any.

MD:
* Looks good, tested `Sonic 3 & Knuckles` and `Crusader of Centy`.

NGP:
* Memory wasn't exposed at all. Tested `Rockman - Battle & Fighters`.

**Comment by barbudreadmon** [comment]
thanks for the feedback, i'll look into this

**Comment by barbudreadmon** [comment]
> SRAM is unmapped ($6000-7FFF)

What i'm exposing should actually be the cartridge's ram usually located at those adresses (it seems to vary on some mappers), does that mean the ram you were expecting is another one ? Maybe the CPU Ram with a size of 0x800 ?

**Comment by Sanaki** [comment]
No, it should be cartridge RAM. Loading up Final Fantasy III will show it's not mapped at all though. Again, this could be a mapper issue of some sort, or something else. I know the save RAM mapping had to be delayed for cores like Mesen to get it to work properly.

**Comment by barbudreadmon** [comment]
Not too sure what's going on but i'm not convinced there is an issue with my code, as a matter of fact when i put the following code in the retro_run, i can confirm the exposed ram for nes & fds isn't static : 
```
	for(int i = 0; i < MainRamSize; i++) {
		int val = ((UINT8*)MainRamData)[i];
		if(val != 0) printf("%02x", val);
	}
	printf("\n");
```
There is a shitload of 0 indeed when loading ff3, but there is also some changing data. 
Note : i think Mesen might not have those 0 because iirc it is randomizing ram's content at boot.

Also, i already looked into the mesen code, that memory mapping is done at boot, in retro_load_game function, i don't see any delaying.

**Comment by Sanaki** [comment]
When loading FF3 NES:
```
[INFO] [RCHEEVOS]: Could not map region starting at $006000
[INFO] [RCHEEVOS]: Registered 0x2000 bytes of SRAM at $006000 (null filler)
...
[INFO] [RCHEEVOS]: All 77 achievements activated for this session (70 unsupported).
```
I may have mixed up Mesen and Sameboy regarding the delay, that one was my mistake. I didn't say FF3 in RetroArch had zeroed the main memory though, just SRAM. Spacegulls is the one that has all memory zeroed.

As for FDS, I did just check the one game. Using the cheat search to explore the memory though, none of it changes at any point.

**Comment by Jamiras** [comment]
I stepped through the memory mapping code for Dragon Warrior IV (NES). The current nightly has no `rarch_memory_descriptor_t`s, so we fall back to calling `retro_get_memory_data`, which is returning 8192 bytes of `RETRO_MEMORY_SYSTEM_RAM`, and 0 bytes of `RETRO_MEMORY_SAVE_RAM`. 
```
...
[INFO] [RCHEEVOS]: Could not map region starting at $006000
[INFO] [RCHEEVOS]: Registered 0x2000 bytes of SRAM at $006000 (null filler)
...
[INFO] [RCHEEVOS]: All 43 achievements activated for this session (41 unsupported).
```
I've also tried refreshing the memory map after running the game for a few minutes and it still doesn't return any `RETRO_MEMORY_SAVE_RAM`.

**Comment by Jamiras** [comment]
Regarding NGP: There's no memory exposed by `retro_memory_descriptor`s or `retro_get_memory_data`. The captured log is just illustrating the double-check that we do in case the memory isn't immediately ready.
```
[INFO] [RCHEEVOS]: got achievements for game id 12895
[INFO] [RCHEEVOS]: Could not map region starting at $000000
[INFO] [RCHEEVOS]: Registered 0x4000 bytes of SYSTEM RAM at $000000 (null filler)
[INFO] [RCHEEVOS]: Posted playing activity
[INFO] [RCHEEVOS]: All 60 achievements activated for this session.
[INFO] [RCHEEVOS]: Load task finished
[INFO] [Vulkan]: VSync => ON
[INFO] [PulseAudio]: Unpausing.
[INFO] [RCHEEVOS]: Could not map region starting at $000000
[INFO] [RCHEEVOS]: Registered 0x4000 bytes of SYSTEM RAM at $000000 (null filler)
[ERROR] [RCHEEVOS]: No memory exposed by core
```
The first check happens when the achievements are fetched from the server. That fails, so we set a flag to check later when the runloop starts, which is the second check. When it fails, we say "no memory exposed by core".

**Comment by barbudreadmon** [comment]
I looked further into nes/fds (i want to figure out this one before looking further into ngp).

Mesen does it like this : https://github.com/libretro/Mesen/blob/master/Libretro/libretro.cpp#L971-L992
It exposes a contiguous CPU Ram + Work Ram + Save Ram split into 0x100 segments => that would be very inconvenient with FBNeo code

QuickNes does it like this : https://github.com/libretro/QuickNES_Core/blob/master/libretro/libretro.cpp#L1113-L1128
The first segment is CPU Ram (0x800), the second is the Work Ram with varying size, no save ram ? => that should be fairly doable, but i'm wondering, does QuickNes expose something in work ram for spacegulls ? I still don't understand why the Work Ram would be empty with current FBNeo code, maybe this game just doesn't use it ?

fceumm does it like this : https://github.com/libretro/libretro-fceumm/blob/master/src/drivers/libretro/libretro.c#L2510-L2578
It basically exposes everything ? => not impossible but is it necessary ?

Here is the list of things i could expose for ff3 : 
```
name nCurrentFrame, len 4
name M6502 #0, len 58
name ptr->nCyclesTotal, len 4
name ptr->nCyclesStall, len 4
name info->APU.squ, len 128
name info->APU.tri, len 24
name info->APU.noi, len 28
name info->APU.dpcm, len 28
name info->APU.regs, len 24
name info->APU.squ, len 128
name info->APU.tri, len 24
name info->APU.noi, len 28
name info->APU.dpcm, len 28
name info->APU.regs, len 24
name frame_irq_flag, len 4
name mode4017, len 4
name step4017, len 4
name clocky, len 4
name cpu_open_bus, len 1
name cyc_counter, len 4
name JoyShifter, len 8
name JoyStrobe, len 1
name CPU Ram, len 2048
name Work Ram, len 8192
name CHR Ram, len 8192
name PRGMap, len 16
name CHRMap, len 32
name CHRType, len 8
name PRGExpMap, len 4
name mapper_regs, len 32
name mapper_regs16, len 64
name mapper_irq_exec, len 4
name mirroring, len 4
name scanline, len 4
name pixel, len 4
name ppu_frame, len 4
name vAddr, len 2
name tAddr, len 2
name vAddr_update, len 2
name vAddr_update_delay, len 4
name fine_x, len 1
name oamAddr, len 1
name ctrl, len 1
name mask, len 1
name status, len 1
name sprite_height, len 4
name v_incr, len 4
name bgtable_start, len 4
name sprtable_start, len 4
name ppu_pal_mask, len 4
name ppu_no_nmi_this_frame, len 4
name ppu_odd, len 4
name ppu_startup, len 4
name ppu_bus_address, len 2
name ppu_over, len 4
name ppu_dbus, len 1
name ppu_buffer, len 1
name write_latch, len 1
name nt_byte, len 1
name bgL, len 1
name bgH, len 1
name bg_shiftL, len 2
name bg_shiftH, len 2
name at_byte, len 1
name at_shiftL, len 1
name at_shiftH, len 1
name at_latchL, len 1
name at_latchH, len 1
name nt_ram, len 4096
name pal_ram, len 32
name oam_ram, len 256
name s-ram, len 8192
```
Different games might have elements added/removed, s-ram appears to be save ram, but for some reason it points to the same ptr as the Work Ram which seems a bit weird (i'll need to ask dink about that).

**Comment by barbudreadmon** [comment]
With https://github.com/libretro/FBNeo/commit/25128c367e4cd6886201cf8166ad3c4972809519, i should be sending exactly the same data as quicknes (i can still add more ptr if necessary). I also did some general fixing/cleanup of the cheevos code.

**Comment by Jamiras** [comment]
I have not actually tried the changes, but they seem reasonable. I also note the change from "Work Ram" to "CPU Ram" for the main system RAM in NES.  If the Save RAM was being exposed instead of the System RAM, that might explain why "Spacegulls for instance always seems to show nothing but zeroes for the memory."

Additionally, that diff makes it easy to spot the problem with SRAM. You're not handling `RETRO_MEMORY_SAVE_RAM` [here](https://github.com/libretro/FBNeo/commit/25128c367e4cd6886201cf8166ad3c4972809519#diff-97ea4ab5097f48cbdf1e07867ad5b4e5beb857161c5897f6a03480e7c0833b71R113). If you do that, you probably don't need to mess with the descriptors.

**Comment by Jamiras** [comment]
We also look for `RETRO_MEMORY_SAVE_RAM` for MegaDrive. It's not necessary for SMS, GG, or NGP.

**Comment by barbudreadmon** [comment]
megadrive ok like this ? https://github.com/libretro/FBNeo/commit/ddc048388ebb075fd59176b6837bbb2055f23fa4

**Comment by Jamiras** [comment]
megadrive system ram `start` should be at 0xFF0000. the save ram is at 0x000000.

the flags should be `RETRO_MEMDESC_SYSTEM_RAM` and `RETRO_MEMDESC_SAVE_RAM`

**Comment by barbudreadmon** [comment]
thanks :)
https://github.com/libretro/FBNeo/commit/8bec5fb0a8f80002f1a679fb02d499b1afd1e74e

**Comment by barbudreadmon** [comment]
Are nes, fds and megadrive working as expected now ?

**Comment by Jamiras** [comment]
NES, FDS, and megadrive appear to be working correctly. Verified save ram is functional in NES and megadrive. Save ram appears to be exposed in FDS, but I didn't really test its functionality.

**Comment by barbudreadmon** [comment]
Nice, i'll look into ngp in the next few days

**Comment by barbudreadmon** [comment]
I think ngp/ngpc achievements will be ok with https://github.com/libretro/FBNeo/commit/bc1591264edcc0415c981c8c66624c0bce2e9dae ? I used https://github.com/libretro/FBNeo/blob/bc1591264edcc0415c981c8c66624c0bce2e9dae/src/burn/drv/pst90s/d_ngp.cpp#L653-L654 as a basis for start adresses.

@Sanaki i also fixed the internal save issue with https://github.com/libretro/FBNeo/commit/c949bffde3453b9c43906f80ae20bfb344dd343d

**Comment by barbudreadmon** [comment]
Btw, while talking about non-arcade retroachievements, i don't see "Sinclair ZX Spectrum" and "Fairchild Channel F" at https://docs.libretro.com/guides/retroachievements/, fwiw i believe retroachievements for those 2 systems should work properly with FBNeo.

**Comment by Sanaki** [comment]
ZX Spectrum and Channel F aren't listed yet because the systems themselves aren't supported yet. That said, yes, they should both be good to go. We need to sort out some details before it'll be viable to open those up for development though.

**Comment by Jamiras** [comment]
> I think ngp/ngpc achievements will be ok with bc15912 ?
Yes. Though there's an error in the RetroAchievements code that's expecting start address to be 0x0000, not 0x4000. I'll get that corrected. 

Verified with the fix that the memory exposed by FBNeo lines up with the memory exposed by MednafenNGP (which uses the RETRO_MEMORY_SYSTEM_RAM interface instead of the memory map, and why the bug didn't affect them).

**Comment by barbudreadmon** [comment]
Can i close or are there still issues ? I see https://docs.libretro.com/guides/retroachievements/ hasn't been updated yet ?

**Comment by Sanaki** [comment]
Should be safe to close. I'll update the docs when I get some spare time, I've been slammed lately. And I'll report back if I stumble into any further issues, of course.
