### ISSUE TITLE
Arcade only DAT file contains wrong "merge" rom entries

### ISSUE THREAD

**Issue by rcasta74** [libretro/FBNeo#794]
Few games contains roms marked as "merge" but they are not listed (or have different name) in "romof" game.
For example:
```
        <game name="emeraldaja" cloneof="emeralda" romof="emeralda">
                <description>Emeraldia (Japan) [Slight GFX Issues]</description>
                <year>1993</year>
                <manufacturer>Namco</manufacturer>
                <rom name="em1-ep0l.6c" size="524288" crc="443f3fce"/>
                <rom name="em1-ep0u.6f" size="524288" crc="484a2a81"/>
                <rom name="em1-ep1l.7c" size="524288" crc="373c1c59"/>
                <rom name="em1-ep1u.7c" size="524288" crc="4e969152"/>
                <rom name="c69.bin" merge="c69.bin" size="16384" crc="349134d9"/>
                <video orientation="horizontal" width="304" height="224" aspectx="4" aspecty="3"/>
                <driver status="good"/>
        </game>
        <game name="emeralda" romof="namcoc70">
                <description>Emeraldia (World) [Slight GFX Issues]</description>
                <year>1993</year>
                <manufacturer>Namco</manufacturer>
                <rom name="em2-ep0l.6c" size="524288" crc="ff1479dc"/>
                <rom name="em2-ep0u.6f" size="524288" crc="ffe750a2"/>
                <rom name="em2-ep1l.7c" size="524288" crc="6c3e5b53"/>
                <rom name="em2-ep1u.7f" size="524288" crc="dee15a81"/>
                <rom name="c70.bin" merge="c70.bin" size="16384" crc="b4015f23"/>
                <video orientation="horizontal" width="304" height="224" aspectx="4" aspecty="3"/>
                <driver status="good"/>
        </game>
```
rom "c69.bin" is marked as merge in game="emeraldaja" but is missing in romof="emeralda"

This is the list of games I have identified with this issue:
- emeraldaj, emeraldaja (romof="emeralda"):  c69.bin (not listed in romof)
- sfz2adl (romof="sfz2al"):  szaj.*, sfz2alj.key (not listed in romof)
- gradiusb (romof="nemesis"):  boot.bin, 400b03.8g (not listed in romof); 400a1.2b, 400a2.1b (listed with different name in romof)

**Comment by barbudreadmon** [comment]
What's the issue here ? Is there any problem with that dat file when using clrmamepro ? Actually, is there any documentation on the dat format ?

**Comment by barbudreadmon** [comment]
Well, MAME is doing exactly the same with its dat files : romof refers to the parent if it exists, and fallback to the bios if a bios exists. The only difference i can see in this specific case is that MAME doesn't seem to reference namcoc69/namcoc70 as bioses for those games (maybe to avoid those dat files inconsistencies ?), but we won't do that in FBNeo.

If you can explain the issue you are encountering because of our current dat files, i can look into it, otherwise i'll consider this as wontfix and i'll close.

**Comment by barbudreadmon** [comment]
>I cannot see any reference to namcoc69 in dat file for these games; is it referenced directly in the code?

Yes, but because there is a parent, we are apparently supposed to put the parent in romof instead, which is pretty weird since that parent uses a different bios...

https://github.com/libretro/FBNeo/blob/bca9175efcd78601f4f1dc997b11c7cc73536e74/src/burn/drv/pst90s/d_namcona1.cpp#L1524
https://github.com/libretro/FBNeo/blob/bca9175efcd78601f4f1dc997b11c7cc73536e74/src/burn/drv/pst90s/d_namcona1.cpp#L1848
