### ISSUE TITLE
Music missing in Phoenix (1980)

### ISSUE THREAD

**Issue by mgtroyas** [libretro/FBNeo#817]
When running Phoenix (1980), just after entering a coin and pressing start, a tune should play, but it's missing.

I tested FBNeo 1.0.0.03 64 bit standalone and music plays, as does in MAME, seems something specific to the libretro core.

**Comment by barbudreadmon** [comment]
Music is playing for me, except if i turn on lowpass filter, is that what you did too ? The issue with lowpass filter is probably also happening on standalone.

**Comment by mgtroyas** [comment]
Mmm on my side on Retroarch core I'm not getting it to play even with FM Interpolation, Sample Interpolation, and Lowpass Filter disabled, neither on 48000 or 44100 sample rates. I deleted my core settings file to go to default and also fails, then simply changed from 48000 to 41000 and also no luck.

On the other hand in standalone it plays on 48000 and 44100 both with and without Lowpass Filter enabled, although in 48000+Lowpass the music is somewhat "metallic" but plays.

**Comment by barbudreadmon** [comment]
After more investigations, it turns out the issue i was mentioning about 48k samplerate + lowpass filter only happens on x86_64 libretro builds. On x86_32 builds, i only get the "metallic" sound you mentioned. I can't reproduce this different x86_32/x86_64 behavior at all on standalone, so maybe there is something about compiler flags, i'll keep investigating.

As for your "no tune at all whatever settings" issue, i tried on linux-x86_64/windows-x86_64/windows-x86_32 libretro builds, and i couldn't reproduce this, so i'm thinking you are maybe using something else ?

**Comment by barbudreadmon** [comment]
> I can't reproduce this different x86_32/x86_64 behavior at all on standalone, so maybe there is something about compiler flags, i'll keep investigating.

@dinkc64 no change when using cflags similar to standalone, nothing with sanitizers either, but i found out that reducing the 0.60 at https://github.com/libretro/FBNeo/blob/955d9f7c776c54fd082ce4459ffcde75d1ca3a65/src/burn/snd/phoenixsound.cpp#L557 somehow fix the 48k+lowpass issue. 

My theory here is that the retroarch frontend is somehow filtering out the sound when using that 0.60 value (i can see the audio buffer i'm sending is populated, so since no sound can be heard i can't think of anything else), maybe because it's saturating (hence the metallic sound) ? It only happens between the moment you press the start button and the moment you can start moving, afterward the sound is playing fine.

**Comment by dinkc64** [comment]
the sound is too loud, when it goes through the lowpass filter (which adds a small gain) it clips terribly thus no sound.  I already fixed it on my side but fix isn't on git yet.  I need your help with something also if you could meet up soon? :)

**Comment by dinkc64** [comment]
oops, I was wrong about phoenix - it actually had a nasty dc offset.  Should be fine now once barbudreadmon moves the files over.

**Comment by dinkc64** [comment]
line 556 is adding the 3 sound channel samples together and dividing it by 4.  usually you divide by the number of channels so they all get equal headroom in the sample, but, the noise channel is slightly louder than the 2 tone channels.

**Comment by mgtroyas** [comment]
> As for your "no tune at all whatever settings" issue, i tried on linux-x86_64/windows-x86_64/windows-x86_32 libretro builds, and i couldn't reproduce this, so i'm thinking you are maybe using something else ?

I'm using windows-x86_64 libretro on Windows 10, nothing fancy. But I did a clean install in another folder and you are right, music plays. Comparing configs I found the source of the problem: it's because of run-ahead in single-instance mode. Tested it and also fails in two-instance mode. As soon as I disable run-ahead, music plays.

**Comment by barbudreadmon** [comment]
oh, indeed, runahead seems to break sound on that one, let us look into it :)

**Comment by dinkc64** [comment]
it's a 2 for 1 bug-fixing special! :)

**Comment by barbudreadmon** [comment]
@mgtroyas the phoenix runahead fix is on git, it should be available from buildbot in the next few hours

**Comment by mgtroyas** [comment]
Finally I was able to test it, and yes music plays now with great quality even with rewind and runahead enabled, great job!

I've played the game a bit more and I'd dare to say the sound effect (squeak) the birds do when hit on levels 3 and 4 (also used on level 5) is a metallic instead of the disturbing but more bird-like standard sound effect. Perhaps another DC bias.

**Comment by dinkc64** [comment]
it looks like the lv3/4 bird sound effect will have to be re-written.  Thanks for letting us know

**Comment by dinkc64** [comment]
It took a lot longer than I expected, but things should be quite nice now.  Please give it a try :)

**Comment by mgtroyas** [comment]
I think it's perfect now, great work!

**Comment by dinkc64** [comment]
excellent, glad to hear it! :)  Thanks for helping us improve the emulation of Phoenix!
