### ISSUE TITLE
Can emscripten compilation support be added

### ISSUE THREAD

**Issue by king2015** [libretro/FBNeo#938]
If this can support emscripten compilation, it will be great.

**Comment by barbudreadmon** [comment]
It fails building (https://git.libretro.com/libretro/FBNeo/-/jobs/1125036) without any explanation.
Except if you know something about this error, i'll probably flag this as wontfix and remove the core from the buildbot. In the first place i'm not even sure emscripten can support the FBNeo core since it has significantly higher requirements than currently working cores.

**Comment by barbudreadmon** [comment]
It was a buildbot issue, it's now building without issue, closing
