### ISSUE TITLE
Add an option, if the roms fails to load, fbneo_libretro can exit with reporting an error

### ISSUE THREAD

**Issue by crashGG** [libretro/FBNeo#977]
I use fbneo_libretro and mame_libretro to launch all arcade games from the command line script, usually fbneo_libretro takes precedence due to more features. But when launching unsupported games, fbneo_libretro stops at this screen:
![astrass-220330-090312](https://user-images.githubusercontent.com/80488411/160763513-21a95925-237b-4664-ba68-d67fb618146d.png)

Hope to add an option to fbneo_libretro to exit immediately on error, and to allow retroarch to return an error code,like %errorlevel% .This way, when the startup script detects this error code, mame_libretro can be switched to start the game.

**Comment by barbudreadmon** [comment]
Sorry but i won't : if i do that i fear all users will disable error messages and we'll get back to square one where i keep getting "game is not working" reports that are only happening because users aren't reading the documentation so they aren't building proper romsets, and aren't reading the logs either.

I understand it's convenient for you to try emulators at random instead of building proper sets, but this is not how you should handle arcade emulation : you should build proper sets for the emulator you are using, as the documentation is telling you to do.

**Comment by crashGG** [comment]
Most of the time we default fbneo to sync with the rom set definition of the latest version of mame, and reuse the entire roms folder. This is the most convenient to maintain, without having to build a separate folder for fbneo, which not only wastes disk space, but also is more troublesome to maintain.
Also, most libretro cores quit on error (incorrect input format, unsupported game). instead of giving an error message to hang. (This is friendly for newbies, but not necessary for veterans who use scripts well and understand how emulators work)
Please,help to add this feature. Maybe as a hidden switch. Like: fbneo-on-error-exit="enabled" written in FinalBurn Neo.opt, not necessarily in retroarch menu.

**Comment by barbudreadmon** [comment]
>Most of the time we default fbneo to sync with the rom set definition of the latest version of mame, and reuse the entire roms folder.

Except FBNeo has a number of exceptions which will never be synced with MAME (cps3, neogeo and pgm bioses, some sega classics, ...), has support for hacks & homebrews that will never be part of MAME, and is not necessarily in sync with MAME (standalone or libretro).

My answer will stay no, i'm locking.
